# Configurações do Repositório
owner: jhonsrodrigues
repo: jhonsrodrigues-status

# Serviços Monitorados
sites:
  - name: Jhons Rodrigues
    url: https://jhonsrodrigues.com
  - name: XYZ Tools
    url: https://xyztools.app

# Configurações da Página Visual
status-website:
  cname: status.jhonsrodrigues.com
  logoUrl: https://tyipxaldonkfqlztqmbk.supabase.co/storage/v1/object/public/public-images/LogotipoJR.png
  name: Status | Jhons Rodrigues
  introTitle: "Painel de controle operacional."
  introMessage: "Monitoramento em tempo real da infraestrutura e serviços ativos. Atualizado a cada 5 minutos."
  theme: light
  
  # Navegação superior
  navbar:
    - title: Status
      href: /
    - title: Site Principal
      href: https://jhonsrodrigues.com
    - title: XYZ Tools
      href: https://xyztools.app
